name: Bug Report
description: File a bug report for Kiro
labels: ["pending-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ---
        ## ⚠️ Before you open this issue

        **Please ensure you're using the latest version of Kiro.** If you're an existing user or have been invited off the waitlist, use the [download links](https://kiro.dev/downloads/) to install or upgrade. Otherwise, join the [waitlist](https://kiro.dev/waitlist/) to get access.

        **Check if your issue is already known.** If so, **subscribe and comment to the following issues for updates** instead of opening a new one:

        [#195: Support for multi-root workspaces](https://github.com/kirodotdev/Kiro/issues/195)
        [#194: Generate Commit Message" button for Kiro's Git integration](https://github.com/kirodotdev/Kiro/issues/194)
        [#87: Remote SSH login issues](https://github.com/kirodotdev/Kiro/issues/87)
        [#31: Provide a token counter in the chat window](https://github.com/kirodotdev/Kiro/issues/31)

        Thank you for helping us keep our issue tracker organized.

        ---
  - type: markdown
    attributes:
      value: |
        **Tip:** Use the `Report a bug / Suggest an idea` button in Kiro to automatically include your system info and conversation ID, then click `Preview on GitHub` to submit.
  - type: checkboxes
    attributes:
      label: |
        Before opening, please confirm:
      options:
        - label: I have [searched for duplicate or closed issues](https://github.com/kirodotdev/Kiro/issues?q=is%3Aissue+)
          required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      description: Your operating system and version
      placeholder: "e.g., macOS 14.2, Windows 11, Ubuntu 22.04"
    validations:
      required: true

  - type: input
    id: kiro-version
    attributes:
      label: Kiro Version
      description: The version of Kiro you're using
      placeholder: "e.g., 1.2.3"
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Describe the issue you encountered
      placeholder: "Describe the bug clearly and concisely. State which feature you used, your intended task, and how the bug affected your workflow."
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Provide steps to reproduce the issue
      placeholder: |
        1. Open Kiro and create/open a project with [specific details]
        2. Perform action [be specific about what you did]
        3. Enter text/command [include exact text if relevant]
        4. Observe [describe the error or unexpected behavior in detail]

        Include any specific code, prompts, or files that are necessary to reproduce the issue.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen
      placeholder: "Explain what Kiro should have done when you performed the actions above. Describe the intended outcome or behavior."
    validations:
      required: true

  - type: textarea
    id: conversation-id
    attributes:
      label: Conversation ID
      description: |
        The conversation ID where the issue occurred (automatically populated when submitted from the IDE)
      placeholder: "e.g., 1234-5678-9876"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Include supporting information that helps diagnose the issue
      placeholder: "Add screenshots, error messages from logs, environment details (large codebase, custom configurations), or workarounds you attempted. This information helps diagnose and resolve the issue."
    validations:
      required: false
